name: Deploy

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시되었을 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 최신 버전 환경에서 실행
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      # 도커 빌드 관련 셋업
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # 내 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 도커이미지 빌드하고 허브로 푸쉬
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . # 현재 디렉토리를 컨텍스트로 사용
          push: true # 이미지를 푸시할 것인지 설정
          platforms: linux/amd64 # 타겟 플랫폼
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}

# Todo: 서버에 도커 이미지 적용되게
# Reference: https://github.com/docker/build-push-action